# Change these first
owner: lenchq # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main page 
    url: https://svo.lol
  - name: Git
    url: https://git.svo.lol
  - name: Wakapi 
    url: https://waka.svo.lol
  - name: Gallery 
    url: https://gallery.svo.lol

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.svo.lol
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Svo.lol uptime status"
  introMessage: Sassy
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
